use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :kyozo_store, KyozoStoreWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [node: ["node_modules/brunch/bin/brunch", "watch", "--stdin",
                    cd: Path.expand("../assets", __DIR__)]]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :kyozo_store, KyozoStoreWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/kyozo_store_web/views/.*(ex)$},
      ~r{lib/kyozo_store_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :kyozo_store, KyozoStore.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "kyozo_store_dev",
  hostname: System.get_env("KYOZO_DB_HOST"),
  username: System.get_env("KYOZO_DB_USER"),
  password: System.get_env("KYOZO_DB_PASS"),
  pool_size: 10

config :guardian, Guardian,
  hooks: GuardianDb,
  allowed_algos: ["HS512"],
  verifify_module: Guardian.JWT,
  issuer: "localhost",
  ttl: { 30, :days },
  allowed_drift: 2000,
  verify_issuer: true,
  secret_key: %{ "alg" => "HS512",
  "k" => "8dmw6P-_8IlVlwpZ2c5BlyXY7E0xvg2-5Xkj_YfbZGlX-QfF7fJiLZSRhqVTeWA9q8a3ntlbqEaxpXvbOt0Wyw",
  "kty" => "oct", "use" => "sig" },
  serializer: KyozoStore.Authenticate.GuardianSerializer
